services:
  - type: web
    name: rag-testcase-backend
    runtime: python
    plan: free
    rootDir: chapter_07_RAG/RAG_TestCase_generator/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.4
